name: sc_error_manager
description: SC Error manager which send errors w/ screenshot to Telegram
version: 0.0.1
author: Andreu Puzikov
homepage: https://github.com/LuckyWins/flutter_sc_error_manager
repository: https://github.com/LuckyWins/flutter_sc_error_manager

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  teledart: ^0.1.3

  screenshot: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
